import minifier from "html-minifier"

export function minify (ctx : Compilation, markup : string) : string {
	return minifier.minify(markup, {
		collapseBooleanAttributes: true,
		collapseWhitespace: true,
		conservativeCollapse: true,
		decodeEntities: true,
		html5: true,
		includeAutoGeneratedTags: false,
		keepClosingSlash: false,
		minifyJS: true,
		quoteCharacter: "\"",
		removeAttributeQuotes: true,
		removeEmptyAttributes: true,
		removeRedundantAttributes: true,
		sortAttributes: true,
		useShortDoctype: true,
	})
		.replace(/<style><\/style>/g, "")
		.replace(/<\/style><style>/g, "")
		.replace(/defer=""/, "defer")
		.replace(/nomodule=""/, "nomodule")
}
